### ISSUE TITLE
Non-versioned DataObject support

### ISSUE THREAD

**Issue by Martimiz** [littlegiant/silverstripe-singlepageadmin#2]
Great litle module - and thanks for the video :)

Would you think it usefull to add support for non-versioned DataObjects? To make it possible to create SiteConfig-like settings on a per-subject base, say 'Product settings', 'OrderSettings'?  

It proved really easy to do - basically just adding a condition like if ($treeClass::has_extension('Versioned')) {... at two locations in doSave...

Obviously 'page' should be replaced by 'object' or something, in naming as well as code, but still... What do you think?

**Comment by stevie-mayhew** [comment]
Do you think this would be handy as a separate module instead? We can fork this off and create it pretty easily.

I think making this one only handle the pages, and having one for objects specifically is a good idea. I might go ahead and do it this afternoon @Martimiz

**Comment by stevie-mayhew** [comment]
@Martimiz https://github.com/Little-Giant/silverstripe-singleobjectadmin

**Comment by Martimiz** [comment]
Hi Stevie

Don't you think the codebase too similar to justify a second module? Or did I miss specific Page related settings in the singlepage module? Or is it maybe just the modulename that would cause confusion?

**Comment by stevie-mayhew** [comment]
Hey @Martimiz 

I'm more of a fan of specific functions for specific goals. There are rarely cases where we require a single object admin, and providing it in this module is beyond the scope of the needs out of which is originally came about.

**Comment by Martimiz** [comment]
My thoughts were that if someone was to use a versioned DataObject for config settings, then both modules would probably be equal - except for the $page variable name. But obviously that is entirely up to you guys and I respect that :)

After seeing your video I now have a lot of new ideas, so many thanks for making this available to the community :)
