### ISSUE TITLE
New object based on defaults

### ISSUE THREAD

**Issue by Martimiz** [littlegiant/silverstripe-singlepageadmin#3]
I thought about a bit of code where a new object/page is created if it doesn't already exist, for instance based on the class $defaults. Someting like

```
$page = $treeClass::get()->first();
if (!isset($page->ID)) {
    $page = singleton($treeClass);
    $defaults = Config::inst()->get($treeClass, 'defaults');
    if (is_array($defaults)) {
        foreach($defaults as $field => $value) $page->$field = $value;
    }
    $page->write();
}
```

What do you think?

**Comment by stevie-mayhew** [comment]
I think it makes sense - it removes the need for us to throw an error as well. Do you want to do up a PR for it?

**Comment by Martimiz** [comment]
Yes, I can do that. I'm really not sure if ->write() is the way to go for versioned objects, so I'll look into that. Might take a couple of days, because things are really busy here at the moment...

**Comment by Martimiz** [comment]
Yes, I can do that. I'm really not sure if ->write() is the way to go for versioned objects, so I'll look into that. Might take a couple of days, because things are really busy here at the moment...

**Comment by Martimiz** [comment]
Yes, I can do that. I'm really not sure if ->write() is the way to go for versioned objects, so I'll look into that. Might take a couple of days, because things are really busy here at the moment...

**Comment by stevie-mayhew** [comment]
Cool, thanks @Martimiz.

We generally follow the lines of doing something like the following to ensure that the write happens in the correct place.

``` php
        $currentStage = Versioned::current_stage();
        Versioned::reading_stage('Stage');
        $object->write();
        $object->doPublish();
        Versioned::reading_stage($currentStage);        
```

**Comment by Martimiz** [comment]
Sorry for being so slow... I finally got around to doing this - and found that it had been done 5 days ago :)

Never got a message from Github though, which I think is strange... But anyway: thanks again for all your work!

Martine

**Comment by stevie-mayhew** [comment]
I guess references to issues don't get pushed through as alerts?

Sorry, I should have closed this one when I pushed the merge above in!

**Comment by Martimiz** [comment]
Seems like they don't... Because I got this message just fine :)
