### ISSUE TITLE
Installer name

### ISSUE THREAD

**Issue by Martimiz** [littlegiant/silverstripe-singlepageadmin#7]
It might be a good idea to change the Composer installername to just singlepageadmin. This could easily be done in composer.json:

```
    "extra": {
            "installer-name": "singlepageadmin"
    }   
```

A lot of people (like me) would change the name anyway - and then the icon will no longer be displayed. 
So you'd have to change SinglePageAdmin.php#13:

```
private static $menu_icon = 'singlepageadmin/images/singlepageadmin.png';
```

**Comment by stevie-mayhew** [comment]
With things being installed in the root at the moment I prefer to prefix the SS modules with `silverstripe-` for my own sanity and knowing they are likely a composer dependency. We could set up a base_dir type situation to solve the problem of an installer path being changed though which would be the more generic solution?

**Comment by Martimiz** [comment]
It was only a suggestion and I totally understand :)

Changing the installer path manually when using composer won't work too well anyway, because composer update just creates a new module - and that is definitely something that nobody wants...

So ignore please. But I'd be interested in how the general point of view on this is, and how it should officially be done if one wanted to. I think I'll ask this on core dev :)

**Comment by stevie-mayhew** [comment]
You can change the installer path by adding the following in your `composer.json`:

``` json

    "extra": {
        "installer-paths": {
            "singlepageadmin": ["littlegiant/silverstripe-singlepageadmin"]
        }
    }
```
